### PR TITLE
Add directory tree

### PR DESCRIPTION
**Pull request by ant31**
- Environment names  are now unique and in the format `/dir1/dir2/name`
- Slug are the name with / replaced by +
- Parents are created or associated from the name. 
  `POST  environments.json?environments[name]=/root/app/production` creates the envs: `/root`, `/root/app` and `/root/app/production`
- Users have permissions on all descendants

### CODE REVIEW

**Comment by ant31** [comment]
why not merge?

**Comment by abodelot** [comment]
I cherry-picked the first commit on master.

For slug management, the gem friendly_id is quite handy : `Model.friendly.find(arg)`  => find either by id or slug. Also the slug is automatically updated when name is changed, and spaces are replaces by `-`.

**Comment by ant31** [comment]
this branch was more than slug

**Comment by ant31** [comment]
parents are contained in the name. it remove the need to post/edut parent id

**Comment by abodelot** [comment]
> parents are contained in the name. it remove the need to post/edut parent id

That could be nice to do wrap this in a custom concern, something like `acts_as_directory`.
- each directory has a unique path 
- name is `basename(path)`
- perform something some kind of `mkdir -p` in before_save callback
- drop ancestry gem (redundant, no need to define ancestorts twice)
- maybe add some restrictions on directory name (case insensitive, forbid some special char that could mess with url-serialization).

**Comment by ant31** [comment]
> - drop ancestry gem (redundant, no need to define ancestorts twice)

Ancestry is use to perform the sql queries (parent/descendants etc).

> - maybe add some restrictions on directory name (case insensitive, forbid some special char that could mess with url-serialization).

I think it's escaped and should work, but we have to test it.

> - name is `basename(path)`

basename is `basename(path)`

> perform something some kind of `mkdir -p` in before_save callback

it's done already

**Comment by abodelot** [comment]
> Ancestry is use to perform the sql queries (parent/descendants etc).

I was implying we'd do it ourselves, to avoid the overhead of mapping names to ids before querying parent or descendants. But that's not really an issue, as we'll only have to deal with a dozen of environments.

**Pull request merged**
